---
services:
#  files-init:
#    build:
#      context: .
#    user: root
#    restart: "no"
#    env_file:
#      .env
#    entrypoint: |
#      /bin/sh -c "chown ftuser:ftuser /generated_data"
#    volumes:
#      - veles-freqtrade-data:/generated_data
  freqtrade:
    # image: freqtradeorg/freqtrade:stable
    # image: freqtradeorg/freqtrade:develop
    # Use plotting image
    # image: freqtradeorg/freqtrade:develop_plot
    # # Enable GPU Image and GPU Resources (only relevant for freqAI)
    # # Make sure to uncomment the whole deploy section
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]
    # Build step - only needed when additional dependencies are needed
    build:
      context: .
    restart: unless-stopped
    container_name: freqtrade-veles_prod
    volumes:
      - veles-freqtrade-data:/freqtrade/generated_data
    # Expose api on port 8080 (localhost only)
    # Please read the https://www.freqtrade.io/en/stable/rest-api/ documentation
    # for more information.
    ports:
      - "127.0.0.1:8080:8080"
    env_file:
      .env
    # Default command used when running `docker compose up`
    command: >
      uv run freqtrade trade
      --logfile /freqtrade/generated_data/freqtrade.log
      --db-url sqlite:////freqtrade/generated_data/tradesv3.sqlite
      --config /freqtrade/user_data/config/user_config_freqai_xgb.json
      --strategy-path /freqtrade/user_data/strategy/
      --strategy XGBoostClassifierStrategy
      --freqaimodel-path /freqtrade/user_data/freqaimodels/
      --freqaimodel XGBoostBinaryClassifier
#    depends_on:
#      - files-init
volumes:
  veles-freqtrade-data: